"""py2app build definition.

    python setup.py py2app -A     # alias build: links back to this checkout
    python setup.py py2app        # standalone build: self-contained .app

**The alias build is the one to use**, including for the copy that lives in
/Applications. It produces a real .app bundle -- which is what macOS attaches
Accessibility and Microphone grants to -- while running against the virtualenv
that `bootstrap.sh` set up.

That matters more here than it would for most apps. A standalone build has to
copy the entire engine stack into the bundle, and the engines are MLX (with its
Metal shader libraries) or CTranslate2 (with its own native extensions). py2app
has no recipe for either, so a standalone bundle of this app is a research
project, and a failed one launches into an ImportError with no traceback.

The trade is that the bundle points at this checkout: move or delete the folder
and the app stops working. `scripts/build_app.sh` warns about that.

Either way the bundle is architecture-specific unless the interpreter it is
built against is universal2 -- so build on each Mac. See docs/ARCHITECTURE.md.
"""

import os

from setuptools import setup
from setuptools.dist import Distribution


class AppDistribution(Distribution):
    """A Distribution that keeps ``install_requires`` away from py2app.

    py2app refuses to run at all when ``install_requires`` is set:

        error: install_requires is no longer supported

    It is not wrong to refuse -- a bundle cannot resolve dependencies at build
    time -- and this setup.py never sets the field. Modern setuptools does, by
    copying ``[project] dependencies`` out of pyproject.toml onto the
    Distribution even for a plain ``setup.py`` invocation. Older setuptools did
    not, which is why the Intel Mac on Python 3.9 built happily and the M1 on
    3.12 did not.

    Both tools are right and they simply disagree, so the dependencies stay in
    pyproject.toml -- that is what ``pip install -e .`` reads, and what
    bootstrap.sh relies on -- and are dropped here, where only the bundle build
    can see the difference. pip never goes through this file.
    """

    def parse_config_files(self, *args, **kwargs):
        super().parse_config_files(*args, **kwargs)
        self.install_requires = []


APP_NAME = "Aloud"
BUNDLE_ID = "com.aloud.Aloud"
VERSION = "0.1.0"

APP = ["Aloud.py"]

PLIST = {
    "CFBundleName": APP_NAME,
    "CFBundleDisplayName": APP_NAME,
    "CFBundleIdentifier": BUNDLE_ID,
    "CFBundleVersion": VERSION,
    "CFBundleShortVersionString": VERSION,
    "CFBundlePackageType": "APPL",
    "NSPrincipalClass": "NSApplication",
    # No LSUIElement. Aloud is a regular app: Dock icon, application menu, a
    # place in the app switcher. The menu bar item is a second surface, set up
    # in code, not the whole interface.
    "LSApplicationCategoryType": "public.app-category.productivity",
    # SF Symbols and NSColor dynamic providers; both are Big Sur and later.
    "LSMinimumSystemVersion": "11.0",
    "NSHighResolutionCapable": True,
    "NSSupportsAutomaticTermination": False,
    "NSSupportsSuddenTermination": False,
    "NSMicrophoneUsageDescription": (
        f"{APP_NAME} records from the microphone while you hold the dictation key."
    ),
    "NSAppleEventsUsageDescription": (
        f"{APP_NAME} sends a paste keystroke to insert your dictated text."
    ),
    "NSHumanReadableCopyright": "",
}

# py2app finds dependencies by walking `import` statements it can see. Several
# framework imports here live inside function bodies -- deliberately, because
# importing AVFoundation or ApplicationServices at module scope costs launch
# time for something that may never be called -- and modulegraph cannot see
# those. Naming them explicitly is what keeps a standalone build from launching
# into an ImportError.
PYOBJC_FRAMEWORKS = [
    "objc",
    "Foundation",
    "AppKit",
    "Quartz",
    "CoreFoundation",
    "ApplicationServices",   # AXIsProcessTrustedWithOptions
    "AVFoundation",          # microphone authorisation
    "CoreMedia",             # AVFoundation's dependency
]

OPTIONS = {
    "argv_emulation": False,  # would install its own event tap and fight ours
    "plist": PLIST,
    "packages": ["aloud", "sounddevice", "cffi"],
    "includes": PYOBJC_FRAMEWORKS + [
        "_cffi_backend",
        "_sounddevice_data",  # the bundled PortAudio dylib
    ],
    "excludes": ["tkinter", "test", "unittest", "pydoc_data"],
    "semi_standalone": False,
}

# Generated by scripts/make_icns.sh; py2app errors out if the path is missing.
if os.path.exists("assets/Aloud.icns"):
    OPTIONS["iconfile"] = "assets/Aloud.icns"


def build() -> None:
    setup(
        name=APP_NAME,
        version=VERSION,
        app=APP,
        options={"py2app": OPTIONS},
        distclass=AppDistribution,
        # No setup_requires: py2app comes from requirements-dev.txt, and asking
        # setuptools to fetch it here goes through the deprecated build-egg
        # path, which prints a wall of warnings before doing nothing useful.
        package_dir={"": "src"},
        packages=["aloud", "aloud.engines", "aloud.ui"],
    )


# Guarded so the tests can import this file and check AppDistribution without
# kicking off a build. Both `python setup.py py2app` and a PEP 517 frontend run
# it as "__main__", so nothing about the real builds changes.
if __name__ == "__main__":
    build()
