"""py2app build definition.

    python setup.py py2app -A     # alias build: links back to this checkout
    python setup.py py2app        # standalone build: self-contained .app

**The alias build is the one to use**, including for the copy that lives in
/Applications. It produces a real .app bundle -- which is what macOS attaches
Accessibility and Microphone grants to -- while running against the virtualenv
that `bootstrap.sh` set up.

That matters more here than it would for most apps. A standalone build has to
copy the entire engine stack into the bundle, and the engines are MLX (with its
Metal shader libraries) or CTranslate2 (with its own native extensions). py2app
has no recipe for either, so a standalone bundle of this app is a research
project, and a failed one launches into an ImportError with no traceback.

The trade is that the bundle points at this checkout: move or delete the folder
and the app stops working. `scripts/build_app.sh` warns about that.

Either way the bundle is architecture-specific unless the interpreter it is
built against is universal2 -- so build on each Mac. See docs/ARCHITECTURE.md.
"""

import os

from setuptools import setup

APP_NAME = "Aloud"
BUNDLE_ID = "com.aloud.Aloud"
VERSION = "0.1.0"

APP = ["Aloud.py"]

PLIST = {
    "CFBundleName": APP_NAME,
    "CFBundleDisplayName": APP_NAME,
    "CFBundleIdentifier": BUNDLE_ID,
    "CFBundleVersion": VERSION,
    "CFBundleShortVersionString": VERSION,
    "CFBundlePackageType": "APPL",
    "NSPrincipalClass": "NSApplication",
    # No LSUIElement. Aloud is a regular app: Dock icon, application menu, a
    # place in the app switcher. The menu bar item is a second surface, set up
    # in code, not the whole interface.
    "LSApplicationCategoryType": "public.app-category.productivity",
    # SF Symbols and NSColor dynamic providers; both are Big Sur and later.
    "LSMinimumSystemVersion": "11.0",
    "NSHighResolutionCapable": True,
    "NSSupportsAutomaticTermination": False,
    "NSSupportsSuddenTermination": False,
    "NSMicrophoneUsageDescription": (
        f"{APP_NAME} records from the microphone while you hold the dictation key."
    ),
    "NSAppleEventsUsageDescription": (
        f"{APP_NAME} sends a paste keystroke to insert your dictated text."
    ),
    "NSHumanReadableCopyright": "",
}

# py2app finds dependencies by walking `import` statements it can see. Several
# framework imports here live inside function bodies -- deliberately, because
# importing AVFoundation or ApplicationServices at module scope costs launch
# time for something that may never be called -- and modulegraph cannot see
# those. Naming them explicitly is what keeps a standalone build from launching
# into an ImportError.
PYOBJC_FRAMEWORKS = [
    "objc",
    "Foundation",
    "AppKit",
    "Quartz",
    "CoreFoundation",
    "ApplicationServices",   # AXIsProcessTrustedWithOptions
    "AVFoundation",          # microphone authorisation
    "CoreMedia",             # AVFoundation's dependency
]

OPTIONS = {
    "argv_emulation": False,  # would install its own event tap and fight ours
    "plist": PLIST,
    "packages": ["aloud", "sounddevice", "cffi"],
    "includes": PYOBJC_FRAMEWORKS + [
        "_cffi_backend",
        "_sounddevice_data",  # the bundled PortAudio dylib
    ],
    "excludes": ["tkinter", "test", "unittest", "pydoc_data"],
    "semi_standalone": False,
}

# Generated by scripts/make_icns.sh; py2app errors out if the path is missing.
if os.path.exists("assets/Aloud.icns"):
    OPTIONS["iconfile"] = "assets/Aloud.icns"

setup(
    name=APP_NAME,
    version=VERSION,
    app=APP,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    package_dir={"": "src"},
    packages=["aloud", "aloud.engines", "aloud.ui"],
)
