"""py2app build definition.

    python setup.py py2app -A     # alias build: fast, links back to this checkout
    python setup.py py2app        # standalone build: self-contained .app

The alias build is the one to use day to day. It produces a real .app bundle,
which is what macOS attaches Accessibility and Microphone grants to, while
still picking up source edits without a rebuild.

The bundle is architecture-specific unless the Python interpreter it is built
against is universal2. Building on each Mac is the simplest route -- see
docs/ARCHITECTURE.md.
"""

import os

from setuptools import setup

APP_NAME = "Murmur"
BUNDLE_ID = "com.murmur.Murmur"
VERSION = "0.1.0"

APP = ["Murmur.py"]

PLIST = {
    "CFBundleName": APP_NAME,
    "CFBundleDisplayName": APP_NAME,
    "CFBundleIdentifier": BUNDLE_ID,
    "CFBundleVersion": VERSION,
    "CFBundleShortVersionString": VERSION,
    # Menu bar only: no Dock icon, no app switcher entry.
    "LSUIElement": True,
    "LSMinimumSystemVersion": "10.15",
    "NSHighResolutionCapable": True,
    "NSMicrophoneUsageDescription": (
        f"{APP_NAME} records from the microphone while you hold the dictation key."
    ),
    "NSAppleEventsUsageDescription": (
        f"{APP_NAME} sends a paste keystroke to insert your dictated text."
    ),
    "NSHumanReadableCopyright": "",
}

OPTIONS = {
    "argv_emulation": False,  # would install its own event tap and fight ours
    "plist": PLIST,
    "packages": ["murmur", "rumps", "sounddevice", "cffi"],
    "includes": ["_cffi_backend"],
    "excludes": ["tkinter", "test", "unittest", "pydoc_data"],
    "semi_standalone": False,
}

# Generated by scripts/make_icns.sh; py2app errors out if the path is missing.
if os.path.exists("assets/Murmur.icns"):
    OPTIONS["iconfile"] = "assets/Murmur.icns"

setup(
    name=APP_NAME,
    version=VERSION,
    app=APP,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    package_dir={"": "src"},
    packages=["murmur", "murmur.engines"],
)
