"""Work out how to link Contents/MacOS/Aloud directly against this machine's
Python, and write the header the launcher includes to find it at runtime.

Run with the project's own interpreter, so every value reflects the venv
actually in use -- not whatever `python3` happens to resolve to on PATH:

    ./.venv/bin/python3 scripts/python_embed_flags.py build/aloud_embed_config.h

Two things come out of this:

1. A header at the given path (``build/aloud_embed_config.h``) with
   ``ALOUD_PYTHONHOME`` and ``ALOUD_PYTHONPATH`` baked in as C string
   literals. The launcher ``setenv()``s them before calling ``Py_BytesMain``.
   PYTHONHOME points at Homebrew's real installation (where the standard
   library lives); PYTHONPATH points at the venv's own site-packages (MLX,
   faster-whisper, PyObjC -- everything `pip install` put there) and this
   checkout's ``src/`` (so `import aloud` resolves the same way it does for
   every other Makefile target, all of which set ``PYTHONPATH=src``
   explicitly rather than depending on the venv's editable install: pip's
   editable installs work by dropping a .pth/finder file in site-packages,
   and .pth files are only processed for directories site.py treats as site
   directories -- which a hand-set PYTHONPATH is not. Pointing PYTHONPATH at
   src/ directly sidesteps that rather than fighting it).

   Both are ordinary absolute paths read at runtime by the interpreter, not
   symlinks inside the bundle -- codesign has no opinion about them, same as
   pyvenv.cfg pointing at Homebrew already didn't.

2. Shell assignments printed to stdout (``CFLAGS=...`` and ``LDFLAGS=...``),
   meant to be ``eval``'d by install_app.sh, telling clang where Python.h
   lives and what to link against.

Homebrew's python@3.12 is a framework build (``--enable-framework``), so
linking is `-framework Python`, not `-lpython3.12` -- the more common route
for a non-framework build (Linux, or a python.org non-framework install) is
kept as a fallback in case that ever isn't true on this machine.
"""

from __future__ import annotations

import shlex
import sys
import sysconfig
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def c_string_literal(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def compile_and_link_flags() -> tuple[str, str]:
    include = sysconfig.get_path("include")
    cflags = f"-I{include}"

    framework_dir = sysconfig.get_config_var("PYTHONFRAMEWORKDIR")
    framework_prefix = sysconfig.get_config_var("PYTHONFRAMEWORKPREFIX")
    if framework_dir and framework_dir != "no-framework" and framework_prefix:
        ldflags = f"-F{framework_prefix} -framework Python -Wl,-rpath,{framework_prefix}"
        return cflags, ldflags

    libdir = sysconfig.get_config_var("LIBDIR")
    ldlibrary = sysconfig.get_config_var("LDLIBRARY") or ""
    name = ldlibrary
    for prefix in ("lib",):
        if name.startswith(prefix):
            name = name[len(prefix):]
    for suffix in (".dylib", ".so", ".a"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    if not libdir or not name:
        raise SystemExit(
            "could not work out how to link against Python: no framework "
            f"(PYTHONFRAMEWORKDIR={framework_dir!r}) and no usable library "
            f"(LIBDIR={libdir!r}, LDLIBRARY={ldlibrary!r})"
        )
    ldflags = f"-L{libdir} -l{name} -Wl,-rpath,{libdir}"
    return cflags, ldflags


def python_home_and_path() -> tuple[str, str]:
    home = sys.base_prefix
    site_packages = sysconfig.get_path("purelib")
    src = str(ROOT / "src")
    pythonpath = f"{site_packages}:{src}"
    return home, pythonpath


def write_header(path: Path, home: str, pythonpath: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "/* generated by scripts/python_embed_flags.py -- do not edit */\n"
        f"#define ALOUD_PYTHONHOME {c_string_literal(home)}\n"
        f"#define ALOUD_PYTHONPATH {c_string_literal(pythonpath)}\n",
        encoding="utf-8",
    )


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: python_embed_flags.py <header-output-path>", file=sys.stderr)
        return 2

    cflags, ldflags = compile_and_link_flags()
    home, pythonpath = python_home_and_path()
    write_header(Path(sys.argv[1]), home, pythonpath)

    print(f"CFLAGS={shlex.quote(cflags)}")
    print(f"LDFLAGS={shlex.quote(ldflags)}")
    print(f"PY_HOME={shlex.quote(home)}")
    print(f"PY_PYTHONPATH={shlex.quote(pythonpath)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
